### ISSUE TITLE
apiVersion change?

### ISSUE THREAD

**Issue by ylcnky** [apk8s/book-source#1]
In the yaml file, `apiVersion: k3s.cattle.io/v1` didn't work. `apiVersion: helm.cattle.io/v1` generated the resource.
https://github.com/apk8s/book-source/blob/ca2031b95ca01cd61f4d224cba845ec056e58db8/chapter-02/k8s/00-cluster/00-cert-manager-helm.yml#L1

**Comment by cjimti** [comment]
thanks @ylcnky
