### ISSUE TITLE
change api version for rbac.authorization.k8s.io/v1beta -> v1, for all files in repo

### ISSUE THREAD

**Issue by sirockin** [apk8s/book-source#3]
The resources with `apiVersioin: rbac.authorization.k8s.io/v1beta` in Chapter 3, and possibly elsewhere, need editing to remove the `beta` suffix from the version

Example:

```
$ kubectl apply -f 06-clusterrole.yml
error: unable to recognize "06-clusterrole.yml": no matches for kind "ClusterRole" in version "rbac.authorization.k8s.io/v1beta1"
```

Solution: Change api version in line 1:
```
apiVersion: rbac.authorization.k8s.io/v1
```

**Comment by cjimti** [comment]
@sirockin Thank you!
